# Generated by Django 3.1.3 on 2021-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210110_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='duration',
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_due',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
