# Generated by Django 3.1.3 on 2021-01-20 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210120_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
