# Generated by Django 3.1.3 on 2021-01-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210120_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_to',
            new_name='assigned_to',
        ),
    ]
