# Generated by Django 3.1.3 on 2021-01-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210120_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='assigned_to',
            new_name='user_assigned',
        ),
    ]
