# Generated by Django 3.1.3 on 2021-01-21 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210120_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
        migrations.AddField(
            model_name='assignment',
            name='final_work',
            field=models.FileField(default='default.txt', upload_to='final_work_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('under_revision', 'under_revision'), ('completed', 'comleted')], default=('pending', 'pending'), max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='due_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('under_review', 'under_review'), ('under_revision', 'under_revision'), ('completed', 'comleted')], default=('pending', 'pending'), max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_file',
            field=models.FileField(upload_to='assignments'),
        ),
    ]
