# Generated by Django 3.1.3 on 2021-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210121_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='final_files'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='final_work',
            field=models.FileField(blank=True, null=True, upload_to='final_work_file'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('under_review', 'under_review'), ('under_revision', 'under_revision'), ('canceled', 'canceled'), ('completed', 'comleted')], default=('pending', 'pending'), max_length=50),
        ),
        migrations.DeleteModel(
            name='Final_copy',
        ),
    ]
