# Generated by Django 3.1.3 on 2020-12-21 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('location', models.CharField(default='Nairobi', max_length=50)),
                ('level', models.CharField(choices=[('beginer', 'beginer'), ('intermediate', 'intermediate'), ('experienced', 'experienced')], default=('beginer', 'beginer'), max_length=50)),
                ('about', models.TextField()),
                ('speciality', models.CharField(default='Fl', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
