# Generated by Django 3.1.3 on 2021-01-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speciality',
        ),
    ]
